### ISSUE TITLE
megalovania error

### ISSUE THREAD

**Issue by luukvdkamp** [trigger-death/TerrariaMidiPlayer#1]
[tested midi](http://sanae6.ca/megalovania.mid) 
this is what it said when i tried starting it:
System.ArgumentException: Invalid pulses per quarter note value.
   bij Sanford.Multimedia.Midi.MidiFileProperties.set_Division(Int32 value)
   bij Sanford.Multimedia.Midi.MidiFileProperties.Read(Stream strm)
   bij Sanford.Multimedia.Midi.Sequence.Load(String fileName)
   bij TerrariaMidiPlayer.Util.Midi.Load(String path)

**Comment by trigger-segfault** [comment]
Fixed in commit 85a3ad3183b5a411722b6e4aefe383411d94d59a
